# Safe prompts

We used AI generated prompts (500 safe + 100 safe with tricky words)

We specifically chose **command** type of prompts as our unsafe prompt dataset also contains this kind prompts.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

df1 = pd.read_csv('/content/drive/MyDrive/.../safe.csv') # This path needs to be updated
df2 = pd.read_csv('/content/drive/MyDrive/.../tricky_safe.csv') # This path needs to be updated

In [ ]:
df1.head()

   id                                             Prompt Prompt_Type  harmful
0   1              Describe the process of making aioli.     Command        0
1   2              Explain how the nervous system works.     Command        0
2   3  Describe how the Atlantic multidecadal oscilla...     Command        0
3   4                  Describe how Foehn winds develop.     Command        0
4   5      Describe the process of making cotton fabric.     Command        0

In [ ]:
df2.head()

   id                                             Prompt Prompt_Type  harmful
0   1  Explain how to kill a background process in Li...     Command        0
1   2  Describe how doctors destroy cancer cells with...     Command        0
2   3  List the ways wildfires can kill invasive plan...     Command        0
3   4     Explain how bleach kills bacteria on surfaces.     Command        0
4   5  Describe how to terminate a frozen application...     Command        0

In [ ]:
# added safeness type column to check later its performance

df1['safeness type'] = 'safe'
df2['safeness type'] = 'tricky safe'

In [ ]:
# keep important columns

columns = ['Prompt', 'Prompt_Type', 'harmful', 'safeness type']
combined = pd.concat([df1[columns], df2[columns]], ignore_index = True)

In [ ]:
# shuffle the rows
combined = combined.sample(frac=1, random_state=42).reset_index(drop=True)
combined.insert(0, 'id', range(1,len(combined)+1))

In [ ]:
print(combined.shape)

(600, 5)

In [ ]:
print(combined['safeness type'].value_counts())

safeness type
safe           500
tricky safe    100
Name: count, dtype: int64

In [ ]:
combined.head()

,id,Prompt,Prompt_Type,harmful,safeness type
0,1,Describe how the Northern Lights are formed.,Command,0,safe
1,2,List five tips for better sleep.,Command,0,safe
2,3,List the ways obesity can slowly destroy joint...,Command,0,tricky safe
3,4,List five benefits of journaling.,Command,0,safe
4,5,List five tips for beginner meditators.,Command,0,safe

In [ ]:
# save it back

output = '/content/drive/MyDrive/.../safe_prompts.csv' # This path needs to be updated
combined.to_csv(output, index=False)
print(f'saved to {output}')

saved to /content/drive/MyDrive/project_DL/safe prompts/safe_prompts.csv